version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: US/Pacific
  open-pull-requests-limit: 10
  reviewers:
  - RevolutionTech
