dist: xenial
language: python
python:
  - 3.8
services:
  - docker

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - cp .env-sample .env

script:
  - poetry run inv check.all
  - poetry run coverage run -m unittest

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: poetry run inv ci-deploy
  on:
    branch: master
