[tool.poetry]
name = "goslinks"
version = "0.0.1"
description = "URL shortener for teams."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1"
pynamodb = "^4.3"
authlib = "^0.14"
google-auth = "^1.11"
google-api-python-client = "^1.8"
python-dotenv = "^0.12.0"
Flask-Testing = "^0.7.1"
flask-wtf = "^0.14.3"
zappa = "^0.51.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0",allow-prereleases = true}
coverage = "^5.0"
pyupgrade = "^1.26"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
