[tool.poetry]
name = "goslinks"
version = "0.0.1"
description = "URL shortener for teams."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1"
pynamodb = "^4.2"
authlib = "^0.12"
google-auth = "^1.6"
google-api-python-client = "^1.7"
python-dotenv = "^0.10.3"
Flask-Testing = "^0.7.1"
flask-wtf = "^0.14.2"
zappa = "^0.48.2"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0",allows-prereleases = true}
coverage = "^4.5"
pyupgrade = "^1.25"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
