# Automatically merge PRs with the "ready" label
name: Automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - unlabeled

jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - uses: squalrus/merge-bot@v0.4.4
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_GITHUB_TOKEN }}
          reviewers: false
          delete_source_branch: false
