name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install

      - run: cp .env-sample .env
      - run: poetry run inv check.all
      - run: poetry run coverage run -m unittest
      - run: poetry run coverage xml
      - uses: codecov/codecov-action@v1.5.0

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    environment: prod
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install

      - run: poetry run inv ci-deploy
        env:
          DECRYPT_PASSWORD: ${{ secrets.DECRYPT_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
